### ISSUE TITLE
Suite descriptions duplicated

### ISSUE THREAD

**Issue by WouterOet** [mscharhag/oleaster#20]
When running a package of test classes in IntelliJ, suite descriptions seem to be duplicated. E.g. when running the tests in the 'oet.wouter.scanner.api' package the result is as follows:

![image](https://cloud.githubusercontent.com/assets/1821137/6546652/ced8b98c-c5bb-11e4-9f84-190c12a44229.png)
 
Although I didn't test it I assume this behavior is also present in other IDE's.

**Comment by mscharhag** [comment]
Fixed in 2356a5c070adf5ca3c8f12eef4e067101c3c4875, Thanks to WouterOet
