### ISSUE TITLE
beforeEachs run in reversed order

### ISSUE THREAD

**Issue by shogowada** [mscharhag/oleaster#25]
When having more than one ```beforeEach``` block like below, it runs them in reversed order. This is different from jasmine's behavior. It seems ```afterEach``` gets executed in order.
```java
@RunWith(OleasterRunner.class)
public class OleasterTest {

  String lhs;
  String rhs;

  String target;

  {
    beforeEach(() -> {
      System.out.println("arrange");
      lhs = "a";
      rhs = "b";
    });

    beforeEach(() -> {
      System.out.println("act");
      target = lhs + rhs;
    });

    it("should be added", () -> {
      expect(target).toEqual(lhs + rhs);
    });
  }
}
```
This will print out ```act``` then ```arrange```, and test is failing unexpectedly.

**Comment by segg3r** [comment]
+1

**Comment by mscharhag** [comment]
You are right. Thanks for reporting this issue.
