### ISSUE TITLE
It should be possible to run a single or selection of tests instead of every test in a file

### ISSUE THREAD

**Issue by peterklijn** [mscharhag/oleaster#29]
When writing unit tests in plain old JUnit, at least in an IDEA it is possible to run a single test. Currently this is not the case for oleaster afaik. Now I understand that this is partly an IDEA thing and this might be seen as out-of-scope for this project. However I would suggest the following:

In Jasmine they have the ['focused specs' concept](http://jasmine.github.io/2.5/focused_specs.html), where you can prefix an `it` with the letter `f`, to run only that block, or prefix a `describe` with the letter `f` to run only that describe block.

**Focussed it**

``` java
describe("The Product class", () -> {
    fit("should be awesome", () -> { // <-- only this it will be ran, every other will be skipped
        Product p = new Product();
        expect(p.areYouAwesome()).toBeTrue();
    });

    describe("nested thing", () -> {
      it("should do 1", () -> {
        expect(true).toBeTrue();
      });

      it("should do 2", () -> {
        expect(false).toBeFalse();
      });
    });
});
```

**Focussed describe**

``` java
describe("The Product class", () -> {
    it("should be awesome", () -> {
        Product p = new Product();
        expect(p.areYouAwesome()).toBeTrue();
    });

    fdescribe("nested thing", () -> { // <-- only the it's in this block will be ran, every other will be skipped
      it("should do 1", () -> {
        expect(true).toBeTrue();
      });

      it("should do 2", () -> {
        expect(false).toBeFalse();
      });
    });
});
```

An interesting alternative, which I prefer since it's more readable, is Mocha (which is a Jasmine alternative), which used the ['exclusive'](https://mochajs.org/#exclusive-tests) and ['inclusive'](https://mochajs.org/#inclusive-tests) concepts:

**exclusive it**

``` java
describe("The Product class", () -> {
    it.only("should be awesome", () -> { // <-- only this it will be ran, every other will be skipped
        Product p = new Product();
        expect(p.areYouAwesome()).toBeTrue();
    });

    describe("nested thing", () -> {
      it("should do 1", () -> {
        expect(true).toBeTrue();
      });

      it("should do 2", () -> {
        expect(false).toBeFalse();
      });
    });
});
```

**exclusive describe**

``` java
describe("The Product class", () -> {
    it("should be awesome", () -> {
        Product p = new Product();
        expect(p.areYouAwesome()).toBeTrue();
    });

    describe.only("nested thing", () -> { // <-- only the it's in this block will be ran, every other will be skipped
      it("should do 1", () -> {
        expect(true).toBeTrue();
      });

      it("should do 2", () -> {
        expect(false).toBeFalse();
      });
    });
});
```

**Inclusion**

``` java
describe("The Product class", () -> {
    it.skip("should be awesome", () -> { // <-- run everything except this it
        Product p = new Product();
        expect(p.areYouAwesome()).toBeTrue();
    });

    describe("nested thing", () -> {
      it("should do 1", () -> {
        expect(true).toBeTrue();
      });

      it("should do 2", () -> {
        expect(false).toBeFalse();
      });
    });
});
```

``` java
describe("The Product class", () -> {
    it("should be awesome", () -> {
        Product p = new Product();
        expect(p.areYouAwesome()).toBeTrue();
    });

    describe.skip("nested thing", () -> { // <-- run everything except this block
      it("should do 1", () -> {
        expect(true).toBeTrue();
      });

      it("should do 2", () -> {
        expect(false).toBeFalse();
      });
    });
});
```

**Comment by peterklijn** [comment]
@mscharhag, can you please respond?

**Comment by brunodles** [comment]
@peterklijn you can create a static method that simply ignore the methods.
Take a look [here](https://github.com/brunodles/OleasterSuiteRunner/blob/master/src/main/java/com/brunodles/oleaster/StaticRunnerHelper.java#L56)

**Comment by marioluan** [comment]
@peterklijn don't know if this is the case, but there's another project from a bigger community under heavy development and which has all those features you need.

[https://github.com/greghaskins/spectrum](https://github.com/greghaskins/spectrum)

**Comment by peterklijn** [comment]
Thanks for the tip @brunodles, I actually already implemented it a while ago :).

Just added a PR a few seconds ago: https://github.com/mscharhag/oleaster/pull/35

Thanks for sharing @marioluan, however I must admit that I'm not the biggest BDD fan. Hopefully my PR will be merged 🤞

**Comment by mscharhag** [comment]
Good suggestion. Thanks for the pull request @peterklijn. I will have a look in the next days.

**Comment by peterklijn** [comment]
@mscharhag did you have a chance to look at the PR already? Is there a way that I can help to speed things up a bit?

**Comment by mscharhag** [comment]
@peterklijn I am sorry that this took (again) longer than expected (which has nothing to do with your pull request). Does it help you, if I create a new release with this pull request?

**Comment by peterklijn** [comment]
That would be great! Thanks

**Comment by mscharhag** [comment]
Added 0.2.0 release containing this and your other pull request. It also available via maven central repository.
